image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake make
  script:
    - cmake .
    - cmake --build .
    - strip aec
    - g++ -o aec.elf AECforWebAssembly.cpp -static -O3
    - strip aec.elf
  artifacts:
    paths:
      - aec
      - aec.elf

test:
  stage: test
  before_script:
    - apt update && apt -y install cmake make nodejs npm # Apparently, those are not saved from the build phase on GitLab.
  script:
    - cmake .
    - ctest --rerun-failed --output-on-failure
